-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 12:01:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geoapp_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geoapp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geoapp_db` DEFAULT CHARACTER SET utf8 ;
USE `geoapp_db` ;

-- -----------------------------------------------------
-- Table `geoapp_db`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoapp_db`.`groups` (
                                                    `id` INT NOT NULL,
                                                    `name` VARCHAR(45) NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `geoapp_db`.`points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoapp_db`.`points` (
                                                    `id` INT NOT NULL,
                                                    `x` FLOAT NULL,
                                                    `y` FLOAT NULL,
                                                    `group_id` INT NOT NULL,
                                                    PRIMARY KEY (`id`),
    INDEX `id_idx` (`group_id` ASC) VISIBLE,
    CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `geoapp_db`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `geoapp_db`.`groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `geoapp_db`;
INSERT INTO `geoapp_db`.`groups` (`id`, `name`, `updated_at`, `deleted_at`) VALUES (1, 'Крым', '2023-05-12 12:30:45', null);
INSERT INTO `geoapp_db`.`groups` (`id`, `name`, `updated_at`, `deleted_at`) VALUES (2, 'Краснодарский Край', '2023-06-12 14:50:31', null);
INSERT INTO `geoapp_db`.`groups` (`id`, `name`, `updated_at`, `deleted_at`) VALUES (3, 'Московская область', '2023-12-20 18:58:40', null);
INSERT INTO `geoapp_db`.`groups` (`id`, `name`, `updated_at`, `deleted_at`) VALUES (4, 'Воронежская область', '2023-12-20 18:58:40', null);
INSERT INTO `geoapp_db`.`groups` (`id`, `name`, `updated_at`, `deleted_at`) VALUES (5, 'Ставропольский край', '2023-12-20 18:58:40', null);

COMMIT;


-- -----------------------------------------------------
-- Data for table `geoapp_db`.`points`
-- -----------------------------------------------------
START TRANSACTION;
USE `geoapp_db`;
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (1, 44.61470403958286, 33.52434498682296, 1);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (2, 44.49385240402408, 34.14631471983443, 1);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (3, 44.94886323147976, 34.10871660993952, 1);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (4, 45.04154096470527, 38.973076229102155, 2);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (5, 45.63789439203227, 38.93063096962156, 2);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (6, 44.74946507791376, 37.775200880308155, 2);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (7, 45.22059924610815, 36.68418910186632, 2);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (8, 55.764718975199365, 37.6117803069226, 3);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (9, 56.356866835727516, 38.21355482996441, 3);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (10, 55.463953219603376, 37.531593303266675, 3);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (11, 51.70507699541208, 39.216045107760394, 4);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (12, 50.3148618890673, 39.44713196786691, 4);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (13, 51.45377062480631, 42.04685914406523, 4);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (14, 45.043724347913745, 41.976540062247444, 5);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (15, 44.10765404067231, 42.982659259142764, 5);
INSERT INTO `geoapp_db`.`points` (`id`, `x`, `y`, `group_id`) VALUES (16, 45.77508990681652, 42.9124833601524, 5);

COMMIT;
